language: python
sudo: false
matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27-dj111
    - python: '3.6'
      env: TOXENV=py36-dj111
    - python: '3.6'
      env: TOXENV=py36-dj22
install:
  - pip install tox
script: tox
